### ISSUE TITLE
Mixed tabs and spaces in example project

### ISSUE THREAD

**Issue by mak448a** [SagaPDev/Godot-SDL-Gamepad-Test#14]
The example project doesn't load because of this.

**Comment by SagaPDev** [comment]
yeah that's probably because i'm using spaces instead of the standard tabs (i was using an external editor while working on this)
you could try to match my settings for this project (revert back when working on other things)
![image](https://github.com/user-attachments/assets/cf1097ab-86da-4eea-9061-8a1724fab0dc)

i'll fix this

**Comment by SagaPDev** [comment]
https://github.com/SagaPDev/Godot-SDL-Gyro/releases/tag/v0.3 fixed example project of this release
